### PR TITLE
Add parameter for whether stepper limits error <= 1

### PR DESCRIPTION
**Pull request by guyer**
Some steppers intrinsically prevent the error from exceeding a threshold.
Other steppers are smoother if they are allowed to drive the error near the target.
Some steppers are hard-wired to be limiting or not, while others can be run in either mode.

### CODE REVIEW

**Comment by tkphd** [comment]
Build error is 
> Orb codacy/coverage-reporter@11.9.0 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.

**Comment by guyer** [comment]
I can't figure out how to opt the orb. Probably the CI should be migrated to GitHub Actions or Azure.

**Comment by guyer** [comment]
Rebase this on #10 (assuming it's accepted)

**Review by tkphd — APPROVED** [review]
LGTM

**Comment by tkphd** [comment]
Tests pass locally on Linux with Python 3.9. 
Flake8 complains about a few formatting choices:
```output
1     E231 missing whitespace after ','
7     E261 at least two spaces before inline comment
7     E305 expected 2 blank lines after class or function definition, found 1
77    F821 undefined name 'stepper'
```

**Comment by guyer** [comment]
> Flake8 complains about a few formatting choices:

Where do you get these linting errors? I don't see them either in the CI (which I think isn't checking very much) or locally (when I don't restrict it at all).

**Comment by tkphd** [comment]
Ah! Looks like it all came from the `build` directory, your code is clean.

**Comment by guyer** [comment]
> your code is clean

Hard to believe, but thanks for confirming

**Pull request merged**
